#+TITLE:  README for the demo-it Project
#+AUTHOR: Howard Abrams
#+EMAIL:  howard.abrams@gmail.com
#+DATE:   2014 Jul 30
#+TAGS:   emacs
#+STARTUP: inlineimages

  When making demonstrations of new products, technologies and other
  geekery, I love the versatility of using Emacs to demonstrate the
  trifecta of sprint reviews:

  - Presentations explaining the technology and whatnot
  - Source code ... correctly highlighted and interactive
  - Reviewing code using a connected REPL
  - Executing the code in Eshell

  However, I don't want to fat-finger, mentally burp, or even delay
  gratification for my audience while I laboriously type, so I
  predefine each "step" as an Elisp function, and then have =demo-it=
  execute each function when I hit the =F6= key.

  - [[https://www.youtube.com/watch?v%3D3T00X_sNg4Q][Learn You Some Lisp for Great Good]]
  - [[https://www.youtube.com/watch?v%3DB6jfrrwR10k][Emacs: An Introduction for the Curious]]

  Using this project is a three step process:

  1. Load the library in your own Elisp source code file
  2. Create a collection of functions that "do things".
  3. Call the =demo-it-start= function with the ordered list of functions.

  For instance:

  #+BEGIN_EXAMPLE
  (load-library "demo-it")   ;; Load this library of functions

  ;; Define the first of many steps that do things.
  (defun my-demo/step-1 ()
    (delete-other-windows)
    (demo/org-presentation "~/presentations/emacs-demo/emacs-demo-start.org"))

  (defun my-demo/step-2 ()
    (demo-it-load-side-window "~/Work/my-proj/src/my-proj.py")
    (demo-it-presentation-advance))

  ;; Wrap the collection of functions in another function...
  (defun my-demo ()
     "My fabulous demonstration."
     (interactive)
     (demo-start (list
                     'my-demo/step-1
                     'my-demo/step-2
                     ;; ...
                   )))

  (my-demo) ;; Optionally start the demo when file is loaded.
#+END_EXAMPLE

  Each "step" is an Elisp functions that does something like load some
  source code, or show off an org-mode file as a presentation.  While
  this package has a collection of helping functions, the steps can
  use any Elisp command to show off a feature.

  For a more complete example, see [[file:example.el][example.el]].

  [[http://youtu.be/TSprQzowhAQ]]

  I recommend installing these other Emacs packages:

  - [[https://github.com/takaxp/org-tree-slide][org-tree-slide-mode]]
  - [[https://github.com/sabof/org-bullets][org-bullets]]
  - [[https://github.com/magnars/expand-region.el][expand-region]]
  - [[https://github.com/Bruce-Connor/fancy-narrow][fancy-narrow]]
